title: try-theme-just-the-docs
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/try-theme-just-the-docs" # subpath e.g. /blog
url: "" # base url e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# site variables
author: Arpit Tripathi

# Theme specific configs
remote_theme: just-the-docs/just-the-docs
aux_links: # Aux links for the upper right navigation
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"
aux_links_new_tab: true # Makes Aux links open in a new tab. Default is false
mermaid:
  # Version of mermaid library : Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.7.0"
nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

